# Generated by scripts/generate_data_model.py; do not edit manually.
# RC ID: RC-213.

from __future__ import annotations

from datetime import datetime
from typing import Any

from pydantic import BaseModel, Field

SCHEMA_VERSION = 1

class WorkspaceData(BaseModel):
    id: str
    owner_id: int
    name: str
    created_at: datetime
    updated_at: datetime
    deleted_at: datetime | None = None
    version: int = 1

class SessionData(BaseModel):
    id: str
    workspace_id: str
    owner_id: int
    title: str | None = None
    status: str = 'active'
    provider_reference_id: str | None = None
    model_manifest_id: str | None = None
    created_at: datetime
    updated_at: datetime
    deleted_at: datetime | None = None
    version: int = 1

class MessageData(BaseModel):
    id: str
    session_id: str
    role: str
    sequence: int
    created_at: datetime
    updated_at: datetime
    deleted_at: datetime | None = None
    version: int = 1

class ContentBlockData(BaseModel):
    id: str
    message_id: str
    ordinal: int
    type: str
    payload_json: dict[str, Any]
    created_at: datetime
    updated_at: datetime
    deleted_at: datetime | None = None
    version: int = 1

class ToolCallData(BaseModel):
    id: str
    message_id: str
    call_id: str
    name: str
    arguments_json: dict[str, Any] = Field(default_factory=dict)
    result_json: dict[str, Any] | None = None
    status: str = 'requested'
    created_at: datetime
    updated_at: datetime
    deleted_at: datetime | None = None
    version: int = 1

class FileSnapshotData(BaseModel):
    id: str
    workspace_id: str
    session_id: str | None = None
    path_ref: str
    content_digest: str
    size_bytes: int
    captured_at: datetime
    deleted_at: datetime | None = None
    version: int = 1

class PromptVersionData(BaseModel):
    id: int
    workspace_id: str
    session_id: str | None = None
    owner_id: int
    original_prompt: str
    optimized_prompt: str
    analysis_json: dict[str, Any]
    provider_reference_id: str | None = None
    model_manifest_id: str | None = None
    accepted: bool = False
    created_at: datetime
    updated_at: datetime
    deleted_at: datetime | None = None
    version: int = 1

class ProviderReferenceData(BaseModel):
    id: str
    workspace_id: str
    provider_name: str
    credential_ref: str | None = None
    base_url: str | None = None
    model_id: str | None = None
    enabled: bool = True
    created_at: datetime
    updated_at: datetime
    deleted_at: datetime | None = None
    version: int = 1

class ModelManifestData(BaseModel):
    id: str
    workspace_id: str
    model_id: str
    revision: str
    sha256: str
    license_id: str
    distribution: str
    runner: str
    context_length: int
    created_at: datetime
    updated_at: datetime
    deleted_at: datetime | None = None
    version: int = 1

class SettingData(BaseModel):
    id: str
    workspace_id: str | None = None
    owner_id: int
    scope: str = 'workspace'
    key: str
    value_json: dict[str, Any]
    created_at: datetime
    updated_at: datetime
    deleted_at: datetime | None = None
    version: int = 1
