-- Generated by scripts/generate_data_model.py; do not edit manually.
-- RC IDs: RC-213, RC-214. Draft migration; RC-214 owns transactional migration execution.
PRAGMA foreign_keys = ON;
BEGIN IMMEDIATE;
CREATE TABLE IF NOT EXISTS schema_migrations (
    version INTEGER PRIMARY KEY,
    applied_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS workspaces (
    id TEXT PRIMARY KEY,
    owner_id INTEGER NOT NULL,
    name TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    deleted_at TEXT,
    version INTEGER NOT NULL DEFAULT 1
);

CREATE INDEX IF NOT EXISTS workspaces_owner_updated ON workspaces(owner_id, updated_at);

CREATE TABLE IF NOT EXISTS sessions (
    id TEXT PRIMARY KEY,
    workspace_id TEXT NOT NULL,
    owner_id INTEGER NOT NULL,
    title TEXT,
    status TEXT NOT NULL DEFAULT 'active',
    provider_reference_id TEXT,
    model_manifest_id TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    deleted_at TEXT,
    version INTEGER NOT NULL DEFAULT 1,
    FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
    FOREIGN KEY (provider_reference_id) REFERENCES provider_references(id) ON DELETE SET NULL,
    FOREIGN KEY (model_manifest_id) REFERENCES model_manifests(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS sessions_workspace_updated ON sessions(workspace_id, updated_at);

CREATE TABLE IF NOT EXISTS messages (
    id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL,
    role TEXT NOT NULL,
    sequence INTEGER NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    deleted_at TEXT,
    version INTEGER NOT NULL DEFAULT 1,
    FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS messages_session_sequence ON messages(session_id, sequence);

CREATE TABLE IF NOT EXISTS content_blocks (
    id TEXT PRIMARY KEY,
    message_id TEXT NOT NULL,
    ordinal INTEGER NOT NULL,
    type TEXT NOT NULL,
    payload_json TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    deleted_at TEXT,
    version INTEGER NOT NULL DEFAULT 1,
    FOREIGN KEY (message_id) REFERENCES messages(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS content_blocks_message_ordinal ON content_blocks(message_id, ordinal);

CREATE TABLE IF NOT EXISTS tool_calls (
    id TEXT PRIMARY KEY,
    message_id TEXT NOT NULL,
    call_id TEXT NOT NULL,
    name TEXT NOT NULL,
    arguments_json TEXT NOT NULL DEFAULT '{}',
    result_json TEXT,
    status TEXT NOT NULL DEFAULT 'requested',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    deleted_at TEXT,
    version INTEGER NOT NULL DEFAULT 1,
    FOREIGN KEY (message_id) REFERENCES messages(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS tool_calls_message_created ON tool_calls(message_id, created_at);

CREATE TABLE IF NOT EXISTS file_snapshots (
    id TEXT PRIMARY KEY,
    workspace_id TEXT NOT NULL,
    session_id TEXT,
    path_ref TEXT NOT NULL,
    content_digest TEXT NOT NULL,
    size_bytes INTEGER NOT NULL,
    captured_at TEXT NOT NULL,
    deleted_at TEXT,
    version INTEGER NOT NULL DEFAULT 1,
    FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
    FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS file_snapshots_workspace_captured ON file_snapshots(workspace_id, captured_at);

CREATE TABLE IF NOT EXISTS prompt_versions_v2 (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    workspace_id TEXT NOT NULL,
    session_id TEXT,
    owner_id INTEGER NOT NULL,
    original_prompt TEXT NOT NULL,
    optimized_prompt TEXT NOT NULL,
    analysis_json TEXT NOT NULL,
    provider_reference_id TEXT,
    model_manifest_id TEXT,
    accepted INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    deleted_at TEXT,
    version INTEGER NOT NULL DEFAULT 1,
    FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
    FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE SET NULL,
    FOREIGN KEY (provider_reference_id) REFERENCES provider_references(id) ON DELETE SET NULL,
    FOREIGN KEY (model_manifest_id) REFERENCES model_manifests(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS prompt_versions_workspace_created ON prompt_versions_v2(workspace_id, created_at);

CREATE TABLE IF NOT EXISTS provider_references (
    id TEXT PRIMARY KEY,
    workspace_id TEXT NOT NULL,
    provider_name TEXT NOT NULL,
    credential_ref TEXT,
    base_url TEXT,
    model_id TEXT,
    enabled INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    deleted_at TEXT,
    version INTEGER NOT NULL DEFAULT 1,
    FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS provider_references_workspace_name ON provider_references(workspace_id, provider_name);

CREATE TABLE IF NOT EXISTS model_manifests (
    id TEXT PRIMARY KEY,
    workspace_id TEXT NOT NULL,
    model_id TEXT NOT NULL,
    revision TEXT NOT NULL,
    sha256 TEXT NOT NULL,
    license_id TEXT NOT NULL,
    distribution TEXT NOT NULL,
    runner TEXT NOT NULL,
    context_length INTEGER NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    deleted_at TEXT,
    version INTEGER NOT NULL DEFAULT 1,
    FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS model_manifests_workspace_model ON model_manifests(workspace_id, model_id);

CREATE TABLE IF NOT EXISTS settings (
    id TEXT PRIMARY KEY,
    workspace_id TEXT,
    owner_id INTEGER NOT NULL,
    scope TEXT NOT NULL DEFAULT 'workspace',
    key TEXT NOT NULL,
    value_json TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    deleted_at TEXT,
    version INTEGER NOT NULL DEFAULT 1,
    FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS settings_scope_key ON settings(scope, owner_id, workspace_id, key);

INSERT OR IGNORE INTO schema_migrations(version, applied_at)
VALUES (2, CURRENT_TIMESTAMP);
PRAGMA user_version = 2;
COMMIT;
