// Generated by scripts/generate_design_tokens.py; do not edit manually.
// RC ID: RC-130.

export const designTokens = {
  "schema_version": 1,
  "themes": {
    "light": {
      "paper": "#faf5eb",
      "paper-deep": "#eee9df",
      "paper-soft": "#f5f0e6",
      "ink": "#432c10",
      "black": "#141413",
      "muted": "#6d6963",
      "line": "#d8d0c2",
      "gold": "#f5cf63",
      "green": "#3adb76",
      "accent-ink": "#141413",
      "surface-contrast": "#141413",
      "surface-copy": "#faf5eb",
      "surface-muted": "#c9c2b6",
      "accent-hover": "#8a5a13",
      "focus-ring": "#6b4500",
      "success-text": "#28643a",
      "success-strong": "#1d7d47",
      "warning-text": "#8a5a13",
      "danger-text": "#7b2f1f",
      "danger-text-strong": "#8e3e2a",
      "danger-muted": "#f2b09d",
      "danger-border": "#c18a75",
      "danger-surface": "#f6e4dc"
    },
    "dark": {
      "paper": "#1c1b18",
      "paper-deep": "#292721",
      "paper-soft": "#24221e",
      "ink": "#f1eadf",
      "black": "#f1eadf",
      "muted": "#b9b0a2",
      "line": "#514b40",
      "gold": "#d7b65a",
      "green": "#3adb76",
      "accent-ink": "#141413",
      "surface-contrast": "#141413",
      "surface-copy": "#f1eadf",
      "surface-muted": "#b4aea1",
      "accent-hover": "#f5cf63",
      "focus-ring": "#f5cf63",
      "success-text": "#8bd39b",
      "success-strong": "#9ae0a8",
      "warning-text": "#f0c96a",
      "danger-text": "#f1b29e",
      "danger-text-strong": "#f2b09d",
      "danger-muted": "#f2b09d",
      "danger-border": "#d88975",
      "danger-surface": "#4a2520"
    }
  },
  "static": {
    "dark-line": "#3b3a35",
    "dark-line-strong": "#514f47",
    "dark-muted": "#b4aea1",
    "dark-copy": "#c9c2b6",
    "success-border": "#8aaf8e",
    "terminal-input": "#26241f",
    "terminal-line": "#4e4a43",
    "terminal-line-strong": "#5f5a50",
    "terminal-text": "#d8d1c4",
    "terminal-placeholder": "#8c867c",
    "terminal-ready": "#cbb477",
    "terminal-running": "#9ac7a0",
    "status-off": "#a49b8b",
    "mockup-bar": "#9e8563",
    "mockup-line": "#d1c5b0",
    "mockup-surface": "#f1ece3",
    "case-1": "#e9e2d5",
    "case-2": "#ddcda6",
    "case-3": "#d5d3c6",
    "case-4": "#d9c6a3",
    "blog-surface": "#e7e0d4",
    "overlay": "rgb(20 18 15 / 62%)",
    "shadow-dialog": "rgb(20 18 15 / 20%)",
    "shadow-offset": "#d7cdbb"
  },
  "dimensions": {
    "font-sans": "Arial, \"Microsoft YaHei\", sans-serif",
    "serif": "Georgia, \"Times New Roman\", serif",
    "mono": "\"IBM Plex Mono\", \"SFMono-Regular\", Consolas, monospace",
    "gutter": "64px",
    "space-1": "4px",
    "space-2": "8px",
    "space-3": "12px",
    "space-4": "16px",
    "space-5": "20px",
    "space-6": "24px",
    "space-7": "32px",
    "space-8": "40px",
    "radius-control": "2px",
    "radius-pill": "999px",
    "shadow-dialog-offset": "12px 12px 0",
    "shadow-mockup-offset": "8px 8px 0",
    "icon-xs": "14px",
    "icon-sm": "16px",
    "icon-md": "18px",
    "icon-lg": "24px",
    "motion-duration": "280ms",
    "motion-ease": "power2.out",
    "rabbit-route-opacity": "0.16",
    "rabbit-empty-opacity": "0.2",
    "rabbit-mono-opacity": "0.12",
    "rabbit-route-size": "56px",
    "rabbit-route-size-small": "32px"
  }
} as const;

export type ThemeTokenName = keyof typeof designTokens.themes.light;
export type StaticTokenName = keyof typeof designTokens.static;
export type DimensionTokenName = keyof typeof designTokens.dimensions;
export type DesignTokenName = ThemeTokenName | StaticTokenName | DimensionTokenName;

export function token(name: DesignTokenName): string {
  return `var(--${name})`;
}
