import { ArrowDownRight, ArrowLeft, ArrowUpRight, ChevronDown, FileText, Search } from "lucide-react";
import { useState, type FormEvent } from "react";

import { PRODUCT_NAME } from "./brand";

// RC ID: RC-054. Render the Rabbit Code brand across the public shell.

type ProductSpec = {
  path: string;
  kicker: string;
  title: string;
  description: string;
  mockup: "workspace" | "evaluation" | "tasks" | "workflow";
  features: string[];
  narrativeTitle: string;
  narrative: string;
  details: string[];
};

const productSpecs: Record<string, ProductSpec> = {
  "/prompt-management": {
    path: "/prompt-management",
    kicker: "PROMPT WORKSPACE",
    title: "Shape prompts with a clear record of every change.",
    description: "Write, score, improve, compare, and export prompts from the same local workspace.",
    mockup: "workspace",
    features: ["Template library", "Category filters", "Prompt analysis", "Rule-based suggestions", "Version history", "Line diffs", "SSE optimization", "Local export", "User-owned records"],
    narrativeTitle: "From first draft to a version you can explain.",
    narrative: "The existing workspace keeps the prompt, analysis, optimized result, and history connected. The redesign changes the reading experience while the API contract remains the same.",
    details: ["Templates are loaded from the FastAPI service.", "Scoring uses the existing eight analysis dimensions.", "Markdown, JSON, TXT, and CSV exports remain available."]
  },
  "/evaluations": {
    path: "/evaluations",
    kicker: "EVALUATIONS",
    title: "Evaluate prompts against the rules that matter.",
    description: "Turn prompt quality into a visible score breakdown, concrete suggestions, and repeatable checks.",
    mockup: "evaluation",
    features: ["Clarity score", "Specificity score", "Context score", "Output format", "Constraint coverage", "Role signals", "Examples", "Executability", "Before and after delta"],
    narrativeTitle: "A score is useful when it points to the next edit.",
    narrative: "The analyzer returns weighted dimensions and a suggestion list. Each result stays close to the original prompt so the person making the edit can judge the tradeoff.",
    details: ["Analysis is available without a remote model.", "The score breakdown is returned by `/api/analyze`.", "Evaluation task support remains available for batches."]
  },
  "/observability": {
    path: "/observability",
    kicker: "RUN HISTORY",
    title: "See what happened to every optimization run.",
    description: "Keep provider choice, latency, fallback status, task state, and saved version in view.",
    mockup: "tasks",
    features: ["Request IDs", "Latency metadata", "Provider requested", "Provider used", "Fallback state", "Task status", "Saved version", "History previews", "Diff output"],
    narrativeTitle: "Local systems should be inspectable by default.",
    narrative: "FastAPI logs request metadata, while the frontend exposes task and version state. This page presents those existing contracts as a calm operations surface.",
    details: ["Request logging is implemented in the FastAPI middleware.", "Background jobs expose queued, running, succeeded, and failed states.", "Remote provider failures can fall back to offline rules."]
  },
  "/dataset-management": {
    path: "/dataset-management",
    kicker: "EVALUATION DATA",
    title: "Collect evaluation prompts without losing their context.",
    description: "Use the repository's evaluation samples and task API as a foundation for repeatable prompt checks.",
    mockup: "evaluation",
    features: ["YAML evaluation set", "Scenario labels", "Before score", "After score", "Score delta", "Provider metadata", "Version reference", "Report output", "Local files"],
    narrativeTitle: "A dataset is a decision record, not a spreadsheet.",
    narrative: "The project already includes evaluation samples and a background evaluation endpoint. The visual template makes those results easier to scan while keeping the underlying data local.",
    details: ["The evaluation dataset lives under `data/evaluation`.", "Reports are generated by the existing CLI flow.", "No new remote storage or CMS is introduced."]
  },
  "/prompt-chaining": {
    path: "/prompt-chaining",
    kicker: "WORKFLOWS",
    title: "Keep long-running prompt work understandable.",
    description: "Follow streaming, background tasks, export jobs, and evaluation runs through one workflow view.",
    mockup: "workflow",
    features: ["SSE stream", "Started event", "Analysis event", "Text chunks", "Fallback event", "Saved event", "Completed event", "Task polling", "Export jobs"],
    narrativeTitle: "The chain is the interface.",
    narrative: "The existing application exposes each optimization path separately. A shared workflow language makes the state transitions legible without changing the server behavior.",
    details: ["Streaming uses `/api/optimize/stream`.", "Background optimization uses `/api/tasks/optimize`.", "Export and evaluation tasks use the same task service boundary."]
  }
};

const blogPosts = [
  ["Architecture", "How the local prompt workspace moves from input to version", "architecture"],
  ["Development plan", "The release path from core rules to a usable web UI", "development-plan"],
  ["Evaluation report", "What the repository's evaluation dataset measures", "evaluation-report"]
] as const;

export function SiteRoute({ path }: { path: string }) {
  const normalized = path.length > 1 ? path.replace(/\/$/, "") : path;
  if (productSpecs[normalized]) return <ProductPage spec={productSpecs[normalized]} />;
  if (normalized === "/") return <HomePage />;
  if (normalized === "/blog") return <BlogIndexPage />;
  if (normalized.startsWith("/blog/")) return <ArticlePage slug={normalized.slice("/blog/".length)} />;
  if (normalized === "/contact") return <ContactPage />;
  return <NotFoundPage path={normalized} />;
}

export function HomePage() {
  return (
    <main className="home-page">
      <section className="home-hero page-grid">
        <div className="home-hero-copy">
          <span className="eyebrow">LOCAL PROMPT ENGINEERING / V3.0</span>
          <h1>The workspace for prompts that need a second pass.</h1>
          <p>Analyze intent, iterate with rules, compare versions, and keep the result close to the work that produced it.</p>
          <div className="hero-actions">
            <a className="action-button action-button-primary" href="/login">LOGIN <ArrowUpRight size={15} /></a>
            <a className="action-button" href="/register">REGISTER <ArrowUpRight size={15} /></a>
          </div>
        </div>
        <a className="paper-preview" href="/prompt-management" aria-label="Open prompt workspace preview">
          <div className="ring-copy ring-copy-top">PROMPT MANAGEMENT · EVALUATION · VERSION CONTROL · </div>
          <div className="artwork-slot">
            <img
              className="rabbit-artwork"
              src="/rabbit-artwork.png"
              alt="PromptLayer 风格复古版画兔兔插画"
              width="643"
              height="684"
              loading="eager"
              decoding="async"
            />
          </div>
          <span className="paper-preview-label">OPEN THE PAPER / VIEW THE WORKSPACE <ArrowUpRight size={16} /></span>
        </a>
      </section>
      <section id="platform-overview" className="overview-section reveal-on-scroll">
        <SectionHeading kicker="PLATFORM OVERVIEW" title="A deliberate path from rough prompt to useful record." />
        <div className="overview-grid">
          <OverviewCard index="01" title="Prompt management" text="Browse local templates, edit a prompt, and run analysis without leaving the workspace." />
          <OverviewCard index="02" title="Evaluation" text="See weighted dimensions, strengths, suggestions, and score deltas instead of one opaque number." />
          <OverviewCard index="03" title="Version control" text="Save optimized prompts, compare history, and export the version in the format you need." />
        </div>
      </section>
      <section className="home-statement reveal-on-scroll">
        <span className="eyebrow">THE LOCAL POSITION</span>
        <h2>Keep the thinking, the change, and the evidence in one place.</h2>
        <a className="text-link" href="/blog/architecture">READ THE ARCHITECTURE NOTES <ArrowUpRight size={15} /></a>
      </section>
    </main>
  );
}

export type AuthMode = "login" | "register";

export function AuthPage({ mode, username, password, loading, error, user, onUsernameChange, onPasswordChange, onSubmit }: {
  mode: AuthMode;
  username: string;
  password: string;
  loading: boolean;
  error: string | null;
  user: { username: string } | null;
  onUsernameChange: (value: string) => void;
  onPasswordChange: (value: string) => void;
  onSubmit: (event: FormEvent<HTMLFormElement>) => void;
}) {
  const isLogin = mode === "login";
  return (
    <main className="auth-page">
      <section className="auth-art-panel">
        <div className="auth-art-copy">
          <span className="eyebrow">LOCAL PROMPT ENGINEERING / V3.0</span>
          <h1>{isLogin ? "Return to the work that matters." : "Make room for a clearer first pass."}</h1>
          <p>{isLogin ? "Continue shaping prompts, comparing versions, and keeping the evidence close to the edit." : "Create a local account for prompt history, saved versions, and an explainable optimization record."}</p>
        </div>
        <div className="auth-artwork-wrap">
          <span className="auth-ring-label">PROMPT MANAGEMENT · EVALUATION · VERSION CONTROL ·</span>
          <img className="auth-rabbit-artwork" src="/rabbit-artwork.png" alt="PromptLayer 风格复古版画兔兔插画" width="643" height="684" loading="eager" decoding="async" />
        </div>
      </section>
      <section className="auth-form-panel">
        <a className="auth-back-link" href="/"><ArrowLeft size={15} /> BACK TO HOME</a>
        <div className="auth-form-heading">
          <span className="eyebrow">{isLogin ? "ACCOUNT LOGIN" : "NEW ACCOUNT"}</span>
          <h2>{isLogin ? "Welcome back." : "Start a local record."}</h2>
          <p>{isLogin ? "Sign in to continue with your saved prompt work." : "Register to keep prompt history and versions attached to your workspace."}</p>
        </div>
        {user ? (
          <div className="auth-success" role="status">
            <strong>Signed in as {user.username}.</strong>
            <a className="action-button action-button-primary" href="/workspace">OPEN WORKSPACE <ArrowUpRight size={15} /></a>
          </div>
        ) : (
          <form className="auth-page-form" onSubmit={onSubmit}>
            <label htmlFor="auth-page-username">USERNAME<input id="auth-page-username" value={username} onChange={(event) => onUsernameChange(event.target.value)} autoComplete="username" required /></label>
            <label htmlFor="auth-page-password">PASSWORD<input id="auth-page-password" type="password" value={password} onChange={(event) => onPasswordChange(event.target.value)} autoComplete={isLogin ? "current-password" : "new-password"} required /></label>
            {error ? <p className="auth-error" role="alert">{error}</p> : null}
            <button className="action-button action-button-primary auth-submit" type="submit" disabled={loading}>{isLogin ? "LOGIN" : "CREATE ACCOUNT"} <ArrowUpRight size={15} /></button>
          </form>
        )}
        <p className="auth-switch">{isLogin ? "Need an account?" : "Already have an account?"} <a href={isLogin ? "/register" : "/login"}>{isLogin ? "REGISTER" : "LOGIN"} <ArrowUpRight size={13} /></a></p>
      </section>
    </main>
  );
}

function ProductPage({ spec }: { spec: ProductSpec }) {
  return (
    <main className="template-page product-page">
      <section className="template-hero">
        <span className="eyebrow">{spec.kicker}</span>
        <h1>{spec.title}</h1>
        <p>{spec.description}</p>
        <div className="hero-actions hero-actions-centered">
          <a className="action-button action-button-primary" href="/workspace">USE THE WORKSPACE <ArrowUpRight size={15} /></a>
          <a className="action-button" href="#features">VIEW FEATURES <ArrowDownRight size={15} /></a>
        </div>
        <ProductMockup variant={spec.mockup} />
      </section>
      <section id="features" className="feature-section reveal-on-scroll">
        <SectionHeading kicker="CAPABILITIES" title={spec.title.split(".")[0] + "."} />
        <div className="feature-grid">
          {spec.features.map((feature, index) => (
            <article className="feature-item" key={feature}>
              <span className="feature-index">{String(index + 1).padStart(2, "0")}</span>
              <h3>{feature}</h3>
              <p>{featureDescription(feature)}</p>
            </article>
          ))}
        </div>
      </section>
      <section className="split-story reveal-on-scroll">
        <div>
          <span className="eyebrow">WHY IT MATTERS</span>
          <h2>{spec.narrativeTitle}</h2>
        </div>
        <div>
          <p>{spec.narrative}</p>
          <ul>
            {spec.details.map((detail) => <li key={detail}>{detail}</li>)}
          </ul>
          <a className="text-link" href="/workspace">TRY IT WITH A REAL PROMPT <ArrowUpRight size={15} /></a>
        </div>
      </section>
      <FAQList title="Frequently asked questions" items={faqFor()} />
    </main>
  );
}

function BlogIndexPage() {
  return (
    <main className="template-page blog-page">
      <section className="template-hero compact-hero blog-hero">
        <span className="eyebrow">BUILD NOTES</span>
        <h1>Notes from the local prompt workspace.</h1>
        <p>Project architecture, development decisions, performance method, and evaluation evidence.</p>
      </section>
      <section className="blog-list reveal-on-scroll">
        {blogPosts.map(([kicker, title, slug], index) => (
          <a className={`blog-item blog-item-${index + 1}`} href={`/blog/${slug}`} key={slug}>
            <span className="eyebrow">{kicker}</span>
            <h2>{title}</h2>
            <ArrowUpRight size={22} />
          </a>
        ))}
      </section>
    </main>
  );
}

function ArticlePage({ slug }: { slug: string }) {
  const article = blogPosts.find(([, , postSlug]) => postSlug === slug) ?? blogPosts[0];
  const body = article[2] === "architecture"
    ? [`${PRODUCT_NAME} uses a local-first split between a Python package and a React web workspace.`, "The analyzer scores a prompt, the suggestion engine turns low dimensions into edits, and the version service stores the result in SQLite.", "The frontend talks to FastAPI through a small typed API boundary. That boundary is the reason the visual shell can change without changing the business workflow."]
    : article[2] === "development-plan"
      ? ["The project grew in layers: core rules, storage and export, CLI and API, then the web UI.", "Each layer keeps its own tests and reuses the same services where possible.", "The V3.0 visual work follows that same constraint: the visual system is shared, while prompt operations stay in the existing workspace."]
      : ["The repository includes more than fifty evaluation samples across technical, business, education, creative, support, data analysis, and long-form scenarios.", "The report records before and after scores, provider, fallback state, and local timing.", "Those records are useful because they show how a prompt changed, not just whether the final text looks different."];
  return (
    <main className="template-page article-page">
      <section className="article-hero">
        <a className="back-link" href="/blog"><ArrowUpRight size={15} className="back-icon" /> BACK TO BUILD NOTES</a>
        <span className="eyebrow">{article[0]}</span>
        <h1>{article[1]}</h1>
        <div className="article-meta"><span>{PRODUCT_NAME}</span><span>LOCAL DOCUMENTATION</span><span>2026</span></div>
      </section>
      <article className="article-body reveal-on-scroll">
        {body.map((paragraph, index) => (
          <div key={paragraph}>
            <h2>{index + 1}. {index === 0 ? "The premise" : index === 1 ? "The record" : "The visual layer"}</h2>
            <p>{paragraph}</p>
          </div>
        ))}
        <div className="article-callout"><FileText size={19} /><span>Source: repository documentation and the existing service boundaries.</span></div>
      </article>
    </main>
  );
}

function ContactPage() {
  const [submitted, setSubmitted] = useState(false);
  function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setSubmitted(true);
  }
  return (
    <main className="template-page contact-page">
      <section className="contact-grid reveal-on-scroll">
        <div className="contact-copy"><span className="eyebrow">CONTACT</span><h1>Bring a prompt worth improving.</h1><p>This local build does not send outbound mail. Use the form to shape a draft, then move it to the repository issue or communication channel you already use.</p><div className="contact-note"><Search size={18} /><span>No external CMS or contact API is configured.</span></div></div>
        <form className="contact-form" onSubmit={submit}>
          <label>Name<input name="name" autoComplete="name" required /></label>
          <label>Context<input name="context" required /></label>
          <label>Message<textarea name="message" rows={7} required /></label>
          <button className="action-button action-button-primary" type="submit">SAVE LOCAL DRAFT <ArrowUpRight size={15} /></button>
          {submitted ? <p className="form-feedback" role="status">Draft captured in this view. Nothing was sent over the network.</p> : null}
        </form>
      </section>
    </main>
  );
}

function NotFoundPage({ path }: { path: string }) {
  return <main className="template-page not-found-page"><span className="eyebrow">404 / ROUTE NOT FOUND</span><h1>{path} is not in the local map.</h1><a className="action-button action-button-primary" href="/">RETURN HOME <ArrowUpRight size={15} /></a></main>;
}

function ProductMockup({ variant }: { variant: ProductSpec["mockup"] }) {
  const labels = variant === "evaluation" ? ["clarity", "specificity", "context", "format"] : variant === "tasks" ? ["queued", "running", "saved", "latency"] : variant === "workflow" ? ["started", "analysis", "chunk", "completed"] : ["templates", "prompt", "score", "history"];
  return <div className={`product-mockup mockup-${variant}`} role="img" aria-label={`${PRODUCT_NAME} interface preview`}><div className="mockup-toolbar"><span /><span /><span /></div><div className="mockup-content"><div className="mockup-sidebar">{labels.map((label) => <span key={label}>{label}</span>)}</div><div className="mockup-main"><div className="mockup-heading">{variant === "evaluation" ? "Prompt score breakdown" : variant === "tasks" ? "Optimization run history" : variant === "workflow" ? "Stream events" : "Master prompt record"}</div><div className="mockup-lines"><i /><i /><i /><i /><i /></div><div className="mockup-data">{labels.map((label, index) => <div key={label}><b>{label}</b><span style={{ width: `${58 + index * 9}%` }} /></div>)}</div></div></div></div>;
}

function SectionHeading({ kicker, title }: { kicker: string; title: string }) {
  return <div className="section-heading reveal-on-scroll"><span className="eyebrow">{kicker}</span><h2>{title}</h2></div>;
}

function OverviewCard({ index, title, text }: { index: string; title: string; text: string }) {
  return <article className="overview-card"><span className="feature-index">{index}</span><h3>{title}</h3><p>{text}</p><ArrowUpRight size={18} /></article>;
}

function FAQList({ title, items }: { title: string; items: string[] }) {
  const [openIndex, setOpenIndex] = useState<number | null>(null);
  return <section className="faq-section"><div className="faq-heading"><span className="eyebrow">FAQ</span><h2>{title}</h2></div><div className="faq-list">{items.map((question, index) => { const answerId = `faq-answer-${index}`; const open = index === openIndex; return <div className="faq-item" key={question}><button type="button" aria-expanded={open} aria-controls={answerId} onClick={() => setOpenIndex(open ? null : index)}><span>{question}</span><ChevronDown size={17} className={open ? "faq-chevron open" : "faq-chevron"} /></button><div id={answerId} className={open ? "faq-answer open" : "faq-answer"} role="region"><p>{faqAnswer(question)}</p></div></div>; })}</div></section>;
}

function faqFor() {
  return ["Where does the prompt data go?", "Can the workspace run without a remote model?", "How is an optimized version saved?", "What happens when a provider fails?"];
}

function faqAnswer(question: string) {
  if (question.includes("where")) return "The default workflow uses the local FastAPI service and its SQLite-backed storage boundary.";
  if (question.includes("remote")) return "The provider registry can construct an HTTP adapter from environment configuration, while the offline provider remains available.";
  if (question.includes("fails")) return "The service records the error summary and can fall back to offline rules for supported flows.";
  return "The current implementation keeps this behavior in the existing API and storage services so the visual layer does not change it.";
}

function featureDescription(feature: string) {
  return `${feature} stays visible as a small, inspectable part of the prompt workflow.`;
}
