import { ArrowDownRight, ArrowUpRight, Check, ChevronDown, FileText, GitBranch, Search, Terminal, Workflow } from "lucide-react";
import { useState, type FormEvent } from "react";

type ProductSpec = {
  path: string;
  kicker: string;
  title: string;
  description: string;
  mockup: "workspace" | "evaluation" | "tasks" | "workflow";
  features: string[];
  narrativeTitle: string;
  narrative: string;
  details: string[];
};

const productSpecs: Record<string, ProductSpec> = {
  "/prompt-management": {
    path: "/prompt-management",
    kicker: "PROMPT WORKSPACE",
    title: "Shape prompts with a clear record of every change.",
    description: "Write, score, improve, compare, and export prompts from the same local workspace.",
    mockup: "workspace",
    features: ["Template library", "Category filters", "Prompt analysis", "Rule-based suggestions", "Version history", "Line diffs", "SSE optimization", "Local export", "User-owned records"],
    narrativeTitle: "From first draft to a version you can explain.",
    narrative: "The existing workspace keeps the prompt, analysis, optimized result, and history connected. The redesign changes the reading experience while the API contract remains the same.",
    details: ["Templates are loaded from the FastAPI service.", "Scoring uses the existing eight analysis dimensions.", "Markdown, JSON, TXT, and CSV exports remain available."]
  },
  "/evaluations": {
    path: "/evaluations",
    kicker: "EVALUATIONS",
    title: "Evaluate prompts against the rules that matter.",
    description: "Turn prompt quality into a visible score breakdown, concrete suggestions, and repeatable checks.",
    mockup: "evaluation",
    features: ["Clarity score", "Specificity score", "Context score", "Output format", "Constraint coverage", "Role signals", "Examples", "Executability", "Before and after delta"],
    narrativeTitle: "A score is useful when it points to the next edit.",
    narrative: "The analyzer returns weighted dimensions and a suggestion list. Each result stays close to the original prompt so the person making the edit can judge the tradeoff.",
    details: ["Analysis is available without a remote model.", "The score breakdown is returned by `/api/analyze`.", "Evaluation task support remains available for batches."]
  },
  "/observability": {
    path: "/observability",
    kicker: "RUN HISTORY",
    title: "See what happened to every optimization run.",
    description: "Keep provider choice, latency, fallback status, task state, and saved version in view.",
    mockup: "tasks",
    features: ["Request IDs", "Latency metadata", "Provider requested", "Provider used", "Fallback state", "Task status", "Saved version", "History previews", "Diff output"],
    narrativeTitle: "Local systems should be inspectable by default.",
    narrative: "FastAPI logs request metadata, while the frontend exposes task and version state. This page presents those existing contracts as a calm operations surface.",
    details: ["Request logging is implemented in the FastAPI middleware.", "Background jobs expose queued, running, succeeded, and failed states.", "Remote provider failures can fall back to offline rules."]
  },
  "/dataset-management": {
    path: "/dataset-management",
    kicker: "EVALUATION DATA",
    title: "Collect evaluation prompts without losing their context.",
    description: "Use the repository's evaluation samples and task API as a foundation for repeatable prompt checks.",
    mockup: "evaluation",
    features: ["YAML evaluation set", "Scenario labels", "Before score", "After score", "Score delta", "Provider metadata", "Version reference", "Report output", "Local files"],
    narrativeTitle: "A dataset is a decision record, not a spreadsheet.",
    narrative: "The project already includes evaluation samples and a background evaluation endpoint. The visual template makes those results easier to scan while keeping the underlying data local.",
    details: ["The evaluation dataset lives under `data/evaluation`.", "Reports are generated by the existing CLI flow.", "No new remote storage or CMS is introduced."]
  },
  "/prompt-chaining": {
    path: "/prompt-chaining",
    kicker: "WORKFLOWS",
    title: "Keep long-running prompt work understandable.",
    description: "Follow streaming, background tasks, export jobs, and evaluation runs through one workflow view.",
    mockup: "workflow",
    features: ["SSE stream", "Started event", "Analysis event", "Text chunks", "Fallback event", "Saved event", "Completed event", "Task polling", "Export jobs"],
    narrativeTitle: "The chain is the interface.",
    narrative: "The existing application exposes each optimization path separately. A shared workflow language makes the state transitions legible without changing the server behavior.",
    details: ["Streaming uses `/api/optimize/stream`.", "Background optimization uses `/api/tasks/optimize`.", "Export and evaluation tasks use the same task service boundary."]
  }
};

const blogPosts = [
  ["Architecture", "How the local prompt workspace moves from input to version", "architecture"],
  ["Development plan", "The release path from core rules to a usable web UI", "development-plan"],
  ["Evaluation report", "What the repository's evaluation dataset measures", "evaluation-report"]
] as const;

const glossaryTerms = [
  ["Clarity", "A prompt's intent is understandable without guesswork."],
  ["Specificity", "The requested task has concrete scope and constraints."],
  ["Context", "The model receives the information needed to act."],
  ["Output format", "The response shape is explicit and testable."],
  ["Constraints", "Boundaries prevent avoidable drift."],
  ["Role", "The prompt gives the task an appropriate point of view."],
  ["Examples", "Representative inputs or outputs remove ambiguity."],
  ["Executability", "The request can be acted on without missing steps."]
] as const;

export function SiteRoute({ path }: { path: string }) {
  const normalized = path.length > 1 ? path.replace(/\/$/, "") : path;
  if (productSpecs[normalized]) return <ProductPage spec={productSpecs[normalized]} />;
  if (normalized === "/") return <HomePage />;
  if (normalized === "/pricing") return <PricingPage />;
  if (normalized === "/case-studies") return <CaseStudiesPage />;
  if (normalized === "/blog") return <BlogIndexPage />;
  if (normalized.startsWith("/blog/")) return <ArticlePage slug={normalized.slice("/blog/".length)} />;
  if (normalized === "/models") return <ModelsPage />;
  if (normalized.startsWith("/models/")) return <ProviderDetailPage slug={normalized.slice("/models/".length)} />;
  if (normalized === "/glossary") return <GlossaryPage />;
  if (normalized.startsWith("/glossary/")) return <GlossaryDetailPage slug={normalized.slice("/glossary/".length)} />;
  if (normalized === "/careers") return <CareersPage />;
  if (normalized === "/contact") return <ContactPage />;
  return <NotFoundPage path={normalized} />;
}

export function HomePage() {
  return (
    <main className="home-page">
      <section className="home-hero page-grid">
        <div className="home-hero-copy">
          <span className="eyebrow">LOCAL PROMPT ENGINEERING / V3.0</span>
          <h1>The workspace for prompts that need a second pass.</h1>
          <p>Analyze intent, iterate with rules, compare versions, and keep the result close to the work that produced it.</p>
          <div className="hero-actions">
            <a className="action-button action-button-primary" href="/prompt-management">OPEN WORKSPACE <ArrowUpRight size={15} /></a>
            <a className="action-button" href="#platform-overview">SEE PLATFORM OVERVIEW <ArrowDownRight size={15} /></a>
          </div>
        </div>
        <a className="paper-preview" href="/prompt-management" aria-label="Open prompt workspace preview">
          <div className="ring-copy ring-copy-top">PROMPT MANAGEMENT · EVALUATION · VERSION CONTROL · </div>
          <div className="artwork-slot">
            <img
              className="rabbit-artwork"
              src="/rabbit-artwork.png"
              alt="PromptLayer 风格复古版画兔兔插画"
              width="643"
              height="684"
              loading="eager"
              decoding="async"
            />
          </div>
          <span className="paper-preview-label">OPEN THE PAPER / VIEW THE WORKSPACE <ArrowUpRight size={16} /></span>
        </a>
      </section>
      <section id="platform-overview" className="overview-section">
        <SectionHeading kicker="PLATFORM OVERVIEW" title="A deliberate path from rough prompt to useful record." />
        <div className="overview-grid">
          <OverviewCard index="01" title="Prompt management" text="Browse local templates, edit a prompt, and run analysis without leaving the workspace." />
          <OverviewCard index="02" title="Evaluation" text="See weighted dimensions, strengths, suggestions, and score deltas instead of one opaque number." />
          <OverviewCard index="03" title="Version control" text="Save optimized prompts, compare history, and export the version in the format you need." />
        </div>
      </section>
      <section className="home-statement">
        <span className="eyebrow">THE LOCAL POSITION</span>
        <h2>Keep the thinking, the change, and the evidence in one place.</h2>
        <a className="text-link" href="/blog/architecture">READ THE ARCHITECTURE NOTES <ArrowUpRight size={15} /></a>
      </section>
    </main>
  );
}

function ProductPage({ spec }: { spec: ProductSpec }) {
  return (
    <main className="template-page product-page">
      <section className="template-hero">
        <span className="eyebrow">{spec.kicker}</span>
        <h1>{spec.title}</h1>
        <p>{spec.description}</p>
        <div className="hero-actions hero-actions-centered">
          <a className="action-button action-button-primary" href="/">USE THE WORKSPACE <ArrowUpRight size={15} /></a>
          <a className="action-button" href="#features">VIEW FEATURES <ArrowDownRight size={15} /></a>
        </div>
        <ProductMockup variant={spec.mockup} />
      </section>
      <section id="features" className="feature-section">
        <SectionHeading kicker="CAPABILITIES" title={spec.title.split(".")[0] + "."} />
        <div className="feature-grid">
          {spec.features.map((feature, index) => (
            <article className="feature-item" key={feature}>
              <span className="feature-index">{String(index + 1).padStart(2, "0")}</span>
              <h3>{feature}</h3>
              <p>{featureDescription(feature)}</p>
            </article>
          ))}
        </div>
      </section>
      <section className="split-story">
        <div>
          <span className="eyebrow">WHY IT MATTERS</span>
          <h2>{spec.narrativeTitle}</h2>
        </div>
        <div>
          <p>{spec.narrative}</p>
          <ul>
            {spec.details.map((detail) => <li key={detail}>{detail}</li>)}
          </ul>
          <a className="text-link" href="/">TRY IT WITH A REAL PROMPT <ArrowUpRight size={15} /></a>
        </div>
      </section>
      <FAQList title="Frequently asked questions" items={faqFor(spec.path)} />
    </main>
  );
}

function PricingPage() {
  const plans = [
    ["LOCAL", "$0", "SQLite history", "Offline rules", "Markdown / JSON / TXT / CSV"],
    ["DEVELOPMENT", "OPEN", "Vite + React", "FastAPI proxy", "Tests and type checks"],
    ["PROVIDER", "CONFIGURED", "HTTP adapter", "Environment keys", "Offline fallback"],
    ["DEPLOYMENT", "YOUR HOST", "Docker image", "Static frontend", "Port 8000 service"]
  ];
  return (
    <main className="template-page pricing-page">
      <section className="template-hero compact-hero">
        <span className="eyebrow">PROJECT SETUP</span>
        <h1>Use the system at the scale your work requires.</h1>
        <p>This repository is MIT-licensed and local-first. The comparison below describes the actual project surfaces, not a hosted billing plan.</p>
      </section>
      <section className="plan-grid">
        {plans.map(([name, price, ...features], index) => (
          <article className={index === 0 ? "plan-card plan-card-highlight" : "plan-card"} key={name}>
            <span className="eyebrow">{name}</span>
            <h2>{price}</h2>
            <ul>{features.map((feature) => <li key={feature}><Check size={14} />{feature}</li>)}</ul>
            <a className="text-link" href={index === 0 ? "/" : "/blog/architecture"}>READ THE NOTES <ArrowUpRight size={14} /></a>
          </article>
        ))}
      </section>
      <FAQList title="Questions about the setup" items={faqFor("/pricing")} />
    </main>
  );
}

function CaseStudiesPage() {
  const cases = [
    ["ENGINEERING", "Code review", "Turn a vague request into a prompt with constraints, edge cases, and a testable output shape."],
    ["BUSINESS", "Sales and planning", "Keep tone, audience, goal, and action request visible before the first rewrite."],
    ["EDUCATION", "Course design", "Move from an audience and topic to learning goals, activities, homework, and assessment."],
    ["CREATIVE", "Story and campaign work", "Compare iterations without losing the first draft or the reason for the change."]
  ];
  return (
    <main className="template-page case-page">
      <section className="template-hero compact-hero">
        <span className="eyebrow">USE CASES</span>
        <h1>Prompt work looks different in every room.</h1>
        <p>These examples are grounded in the repository's built-in templates and evaluation categories.</p>
      </section>
      <section className="case-grid">
        {cases.map(([kicker, title, text], index) => (
          <article className={`case-item case-item-${index + 1}`} key={title}>
            <span className="eyebrow">{kicker}</span>
            <h2>{title}</h2>
            <p>{text}</p>
            <span className="case-arrow"><ArrowUpRight size={20} /></span>
          </article>
        ))}
      </section>
    </main>
  );
}

function BlogIndexPage() {
  return (
    <main className="template-page blog-page">
      <section className="template-hero compact-hero blog-hero">
        <span className="eyebrow">BUILD NOTES</span>
        <h1>Notes from the local prompt workspace.</h1>
        <p>Project architecture, development decisions, performance method, and evaluation evidence.</p>
      </section>
      <section className="blog-list">
        {blogPosts.map(([kicker, title, slug], index) => (
          <a className={`blog-item blog-item-${index + 1}`} href={`/blog/${slug}`} key={slug}>
            <span className="eyebrow">{kicker}</span>
            <h2>{title}</h2>
            <ArrowUpRight size={22} />
          </a>
        ))}
      </section>
    </main>
  );
}

function ArticlePage({ slug }: { slug: string }) {
  const article = blogPosts.find(([, , postSlug]) => postSlug === slug) ?? blogPosts[0];
  const body = article[2] === "architecture"
    ? ["Prompt Optimizer uses a local-first split between a Python package and a React web workspace.", "The analyzer scores a prompt, the suggestion engine turns low dimensions into edits, and the version service stores the result in SQLite.", "The frontend talks to FastAPI through a small typed API boundary. That boundary is the reason the visual shell can change without changing the business workflow."]
    : article[2] === "development-plan"
      ? ["The project grew in layers: core rules, storage and export, CLI and API, then the web UI.", "Each layer keeps its own tests and reuses the same services where possible.", "The V3.0 visual work follows that same constraint: the visual system is shared, while prompt operations stay in the existing workspace."]
      : ["The repository includes more than fifty evaluation samples across technical, business, education, creative, support, data analysis, and long-form scenarios.", "The report records before and after scores, provider, fallback state, and local timing.", "Those records are useful because they show how a prompt changed, not just whether the final text looks different."];
  return (
    <main className="template-page article-page">
      <section className="article-hero">
        <a className="back-link" href="/blog"><ArrowUpRight size={15} className="back-icon" /> BACK TO BUILD NOTES</a>
        <span className="eyebrow">{article[0]}</span>
        <h1>{article[1]}</h1>
        <div className="article-meta"><span>Prompt Optimizer</span><span>LOCAL DOCUMENTATION</span><span>2026</span></div>
      </section>
      <article className="article-body">
        {body.map((paragraph, index) => (
          <div key={paragraph}>
            <h2>{index + 1}. {index === 0 ? "The premise" : index === 1 ? "The record" : "The visual layer"}</h2>
            <p>{paragraph}</p>
          </div>
        ))}
        <div className="article-callout"><FileText size={19} /><span>Source: repository documentation and the existing service boundaries.</span></div>
      </article>
    </main>
  );
}

function ModelsPage() {
  const providers = [
    ["offline", "Offline rules", "The default provider uses the optimizer and analyzer locally."],
    ["http-adapter", "HTTP provider adapter", "Remote providers are configured from environment variables when needed."],
    ["fallback", "Fallback path", "A provider failure can return to the offline rule provider."],
    ["stream", "Streaming path", "The SSE endpoint exposes analysis, chunks, saved, and completed events."]
  ];
  return (
    <main className="template-page index-page">
      <section className="template-hero compact-hero">
        <span className="eyebrow">PROVIDER INDEX</span>
        <h1>Model access without losing local control.</h1>
        <p>The current registry always includes the offline provider and can construct an HTTP adapter from environment configuration.</p>
      </section>
      <AlphabetBar />
      <section className="index-grid">
        {providers.map(([slug, title, text], index) => (
          <a className="index-item" href={`/models/${slug}`} key={slug}>
            <span className="index-number">{String(index + 1).padStart(2, "0")}</span>
            <h2>{title}</h2>
            <p>{text}</p>
            <span className="square-arrow"><ArrowUpRight size={15} /></span>
          </a>
        ))}
      </section>
    </main>
  );
}

function ProviderDetailPage({ slug }: { slug: string }) {
  const title = slug === "offline" ? "Offline rules" : slug === "http-adapter" ? "HTTP provider adapter" : slug === "fallback" ? "Fallback path" : "Streaming path";
  const paragraphs = slug === "offline"
    ? ["The offline provider combines the analyzer and optimizer already present in the backend.", "It is the default for local development and remains available when remote provider configuration is absent."]
    : ["The provider registry creates an HTTP adapter from environment variables named for the requested provider.", "The service records provider requested, provider used, latency, and fallback metadata alongside the saved version."];
  return <DetailPage kicker="PROVIDER DETAIL" title={title} definition="A documented entry in the Prompt Optimizer provider boundary." paragraphs={paragraphs} related={["Prompt workspace", "Evaluations", "Background tasks"]} />;
}

function GlossaryPage() {
  return (
    <main className="template-page index-page glossary-page">
      <section className="template-hero compact-hero">
        <span className="eyebrow">PROMPT GLOSSARY</span>
        <h1>Eight dimensions for a prompt worth iterating.</h1>
        <p>The glossary follows the scoring dimensions used by the existing analyzer.</p>
      </section>
      <AlphabetBar />
      <section className="glossary-grid">
        {glossaryTerms.map(([title, text], index) => (
          <a className="glossary-item" href={`/glossary/${title.toLowerCase().replace(" ", "-")}`} key={title}>
            <span className="index-number">{String(index + 1).padStart(2, "0")}</span>
            <h2>{title}</h2>
            <p>{text}</p>
            <span className="square-arrow"><ArrowUpRight size={15} /></span>
          </a>
        ))}
      </section>
    </main>
  );
}

function GlossaryDetailPage({ slug }: { slug: string }) {
  const term = glossaryTerms.find(([title]) => title.toLowerCase().replace(" ", "-") === slug) ?? glossaryTerms[0];
  return <DetailPage kicker="GLOSSARY DETAIL" title={term[0]} definition={term[1]} paragraphs={[`${term[0]} is one of the dimensions returned by the analyzer and shown in the workspace score breakdown.`, "The purpose of a dimension is to give the next edit a name, a reason, and a measurable place in the history record."]} related={glossaryTerms.slice(0, 3).map(([title]) => title)} />;
}

function DetailPage({ kicker, title, definition, paragraphs, related }: { kicker: string; title: string; definition: string; paragraphs: string[]; related: string[] }) {
  return (
    <main className="template-page detail-page">
      <section className="detail-hero">
        <span className="eyebrow">{kicker}</span>
        <h1>{title}</h1>
        <p>{definition}</p>
      </section>
      <article className="detail-body">
        {paragraphs.map((paragraph, index) => <div key={paragraph}><h2>{index + 1}. {index === 0 ? "What it means" : "How it appears in the system"}</h2><p>{paragraph}</p></div>)}
        <div className="related-terms"><span className="eyebrow">RELATED ENTRIES</span>{related.map((entry) => <a href="/glossary" key={entry}>{entry} <ArrowUpRight size={13} /></a>)}</div>
      </article>
    </main>
  );
}

function CareersPage() {
  return (
    <main className="template-page careers-page">
      <section className="template-hero compact-hero">
        <span className="eyebrow">CONTRIBUTORS</span>
        <h1>Build a clearer open-source prompt workflow.</h1>
        <p>This project is maintained as a local-first MIT codebase. There is no remote hiring pipeline configured in the application.</p>
      </section>
      <section className="careers-grid">
        <div><GitBranch size={22} /><h2>Work in the repository</h2><p>Core rules, services, API, CLI, frontend, tests, docs, and CI are all visible in one place.</p></div>
        <div><Terminal size={22} /><h2>Keep claims executable</h2><p>Performance numbers and provider behavior stay tied to commands and local evidence.</p></div>
        <div><Workflow size={22} /><h2>Improve the loop</h2><p>Make the next prompt edit easier to understand, run, compare, and export.</p></div>
      </section>
    </main>
  );
}

function ContactPage() {
  const [submitted, setSubmitted] = useState(false);
  function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setSubmitted(true);
  }
  return (
    <main className="template-page contact-page">
      <section className="contact-grid">
        <div className="contact-copy"><span className="eyebrow">CONTACT</span><h1>Bring a prompt worth improving.</h1><p>This local build does not send outbound mail. Use the form to shape a draft, then move it to the repository issue or communication channel you already use.</p><div className="contact-note"><Search size={18} /><span>No external CMS or contact API is configured.</span></div></div>
        <form className="contact-form" onSubmit={submit}>
          <label>Name<input name="name" autoComplete="name" required /></label>
          <label>Context<input name="context" required /></label>
          <label>Message<textarea name="message" rows={7} required /></label>
          <button className="action-button action-button-primary" type="submit">SAVE LOCAL DRAFT <ArrowUpRight size={15} /></button>
          {submitted ? <p className="form-feedback" role="status">Draft captured in this view. Nothing was sent over the network.</p> : null}
        </form>
      </section>
    </main>
  );
}

function NotFoundPage({ path }: { path: string }) {
  return <main className="template-page not-found-page"><span className="eyebrow">404 / ROUTE NOT FOUND</span><h1>{path} is not in the local map.</h1><a className="action-button action-button-primary" href="/">RETURN HOME <ArrowUpRight size={15} /></a></main>;
}

function ProductMockup({ variant }: { variant: ProductSpec["mockup"] }) {
  const labels = variant === "evaluation" ? ["clarity", "specificity", "context", "format"] : variant === "tasks" ? ["queued", "running", "saved", "latency"] : variant === "workflow" ? ["started", "analysis", "chunk", "completed"] : ["templates", "prompt", "score", "history"];
  return <div className={`product-mockup mockup-${variant}`} aria-label="Prompt Optimizer interface preview"><div className="mockup-toolbar"><span /><span /><span /></div><div className="mockup-content"><div className="mockup-sidebar">{labels.map((label) => <span key={label}>{label}</span>)}</div><div className="mockup-main"><div className="mockup-heading">{variant === "evaluation" ? "Prompt score breakdown" : variant === "tasks" ? "Optimization run history" : variant === "workflow" ? "Stream events" : "Master prompt record"}</div><div className="mockup-lines"><i /><i /><i /><i /><i /></div><div className="mockup-data">{labels.map((label, index) => <div key={label}><b>{label}</b><span style={{ width: `${58 + index * 9}%` }} /></div>)}</div></div></div></div>;
}

function SectionHeading({ kicker, title }: { kicker: string; title: string }) {
  return <div className="section-heading"><span className="eyebrow">{kicker}</span><h2>{title}</h2></div>;
}

function OverviewCard({ index, title, text }: { index: string; title: string; text: string }) {
  return <article className="overview-card"><span className="feature-index">{index}</span><h3>{title}</h3><p>{text}</p><ArrowUpRight size={18} /></article>;
}

function AlphabetBar() {
  return <nav className="alphabet-bar" aria-label="Alphabetical index">{"ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("").map((letter) => <a href={`#letter-${letter}`} key={letter}>{letter}</a>)}</nav>;
}

function FAQList({ title, items }: { title: string; items: string[] }) {
  const [openIndex, setOpenIndex] = useState<number | null>(null);
  return <section className="faq-section"><div className="faq-heading"><span className="eyebrow">FAQ</span><h2>{title}</h2></div><div className="faq-list">{items.map((question, index) => { const answerId = `faq-answer-${index}`; const open = index === openIndex; return <div className="faq-item" key={question}><button type="button" aria-expanded={open} aria-controls={answerId} onClick={() => setOpenIndex(open ? null : index)}><span>{question}</span><ChevronDown size={17} className={open ? "faq-chevron open" : "faq-chevron"} /></button><div id={answerId} className={open ? "faq-answer open" : "faq-answer"} role="region"><p>{faqAnswer(question)}</p></div></div>; })}</div></section>;
}

function faqFor(path: string) {
  if (path === "/pricing") return ["What does local-first mean here?", "Can I configure a remote provider?", "Where does history live?", "How are exports generated?"];
  return ["Where does the prompt data go?", "Can the workspace run without a remote model?", "How is an optimized version saved?", "What happens when a provider fails?"];
}

function faqAnswer(question: string) {
  if (question.includes("where")) return "The default workflow uses the local FastAPI service and its SQLite-backed storage boundary.";
  if (question.includes("remote")) return "The provider registry can construct an HTTP adapter from environment configuration, while the offline provider remains available.";
  if (question.includes("fails")) return "The service records the error summary and can fall back to offline rules for supported flows.";
  return "The current implementation keeps this behavior in the existing API and storage services so the visual layer does not change it.";
}

function featureDescription(feature: string) {
  return `${feature} stays visible as a small, inspectable part of the prompt workflow.`;
}
