// RC ID: RC-062. API DTOs are generated from the versioned OpenAPI contract.
export type {
  AnalyzeRequest,
  AuthRequest,
  AuthResponse,
  DiffResult,
  EvaluateTaskRequest,
  ExportRequest,
  HTTPValidationError,
  OptimizationSuggestion,
  OptimizeMetadata,
  OptimizeRequest,
  OptimizeResponse,
  ProjectSpace,
  PromptAnalysis,
  PromptTemplate,
  PromptVersion,
  ScoreBreakdown,
  ScoreDimension,
  TaskCreateResponse,
  TaskRecord,
  UserPublic,
  ValidationError,
  VersionSummary
} from "./generated/schema";
