#!/usr/bin/env python3
"""RC ID: RC-126. Generate and validate the route-level Rabbit coverage matrix."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "docs" / "design" / "rabbit-coverage-matrix.json"
OUTPUT = ROOT / "docs" / "design" / "rabbit-coverage-matrix.md"
APP = ROOT / "frontend" / "src" / "App.tsx"
REQUIRED_FIELDS = ("path", "variant", "position", "desktop", "responsive", "themes", "alt", "snapshot")


def load_manifest() -> dict[str, object]:
    return json.loads(MANIFEST.read_text(encoding="utf-8"))


def validate(document: dict[str, object]) -> list[str]:
    errors: list[str] = []
    routes = document.get("routes")
    if not isinstance(routes, list) or not routes:
        return ["routes must be a non-empty array"]
    paths: set[str] = set()
    for route in routes:
        if not isinstance(route, dict):
            errors.append("each route must be an object")
            continue
        missing = [field for field in REQUIRED_FIELDS if not isinstance(route.get(field), str) or not route[field].strip()]
        if missing:
            errors.append(f"{route.get('path', '<unknown>')}: missing {', '.join(missing)}")
        path = route.get("path")
        if isinstance(path, str) and path in paths:
            errors.append(f"duplicate route: {path}")
        if isinstance(path, str):
            paths.add(path)
    app_paths = {"/"} | set(re.findall(r'pathname\s*===\s*"(/[^"?]*)"', APP.read_text(encoding="utf-8")))
    missing_routes = sorted(app_paths - paths)
    errors.extend(f"route missing from coverage matrix: {path}" for path in missing_routes)
    return errors


def render(document: dict[str, object]) -> str:
    routes = document["routes"]
    assert isinstance(routes, list)
    lines = [
        "# Rabbit 路由覆盖矩阵",
        "",
        "<!-- Generated by scripts/check_rabbit_coverage_matrix.py; do not edit manually. -->",
        "",
        f"- 路由数：{len(routes)}",
        "- 每行必须包含素材变体、位置、尺寸、主题、响应式行为、替代文本和视觉快照 ID。",
        "",
        "| 路由 | 变体 | 位置 | Desktop | 响应式 | 主题 | 替代文本 | 快照 ID |",
        "| --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for route in routes:
        assert isinstance(route, dict)
        lines.append("| " + " | ".join(str(route[field]).replace("|", "\\|") for field in REQUIRED_FIELDS) + " |")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    try:
        document = load_manifest()
        errors = validate(document)
    except (OSError, json.JSONDecodeError) as error:
        print(f"ERROR: cannot read coverage manifest: {error}")
        return 1
    if errors:
        for error in errors:
            print(f"ERROR: {error}")
        return 1
    rendered = render(document)
    if args.write:
        OUTPUT.write_text(rendered, encoding="utf-8")
        print(f"Wrote {OUTPUT.relative_to(ROOT).as_posix()}")
        return 0
    if args.check and OUTPUT.read_text(encoding="utf-8") != rendered:
        print("ERROR: route coverage matrix is stale; run with --write")
        return 1
    print(f"Rabbit route coverage matrix is current ({len(document['routes'])} routes).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
