#!/usr/bin/env python3
"""RC ID: RC-032. Reconcile direct dependencies and generate third-party notices."""

from __future__ import annotations

import argparse
import json
import re
import sys
import tomllib
from pathlib import Path

import yaml

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
REGISTER_PATH = REPOSITORY_ROOT / "docs/research/third-party-register.yml"
NOTICE_PATH = REPOSITORY_ROOT / "THIRD_PARTY_NOTICES.md"


def _package_name(spec: str) -> str:
    return re.split(r"[<>=!~\[; ]", spec, maxsplit=1)[0]


def _version_spec(spec: str) -> str:
    name = _package_name(spec)
    return spec[len(name) :].strip() or "unspecified"


def declared_dependencies() -> set[tuple[str, str, str]]:
    backend = tomllib.loads((REPOSITORY_ROOT / "backend/pyproject.toml").read_text(encoding="utf-8"))
    project = backend["project"]
    result = {("pypi", _package_name(spec), _version_spec(spec)) for spec in project["dependencies"]}
    result.update(("pypi", _package_name(spec), _version_spec(spec)) for spec in project["optional-dependencies"]["dev"])
    result.add(("pypi", "hatchling", "unspecified"))
    frontend = json.loads((REPOSITORY_ROOT / "frontend/package.json").read_text(encoding="utf-8"))
    for section in ("dependencies", "devDependencies"):
        result.update(("npm", name, spec) for name, spec in frontend[section].items())
    return result


def load_register() -> dict:
    payload = yaml.safe_load(REGISTER_PATH.read_text(encoding="utf-8"))
    if payload.get("schema_version") != 1 or payload.get("rc_id") != "RC-032":
        raise ValueError("invalid RC-032 third-party register")
    if payload.get("reused_sources") != []:
        raise ValueError("reused_sources must be an explicit empty list")
    return payload


def validate(payload: dict) -> list[str]:
    expected = declared_dependencies()
    entries = payload.get("dependencies", [])
    by_key = {(entry.get("ecosystem"), entry.get("name")): entry for entry in entries}
    errors: list[str] = []
    for ecosystem, name, spec in expected:
        entry = by_key.get((ecosystem, name))
        if entry is None:
            errors.append(f"unregistered dependency: {ecosystem}:{name}")
            continue
        if entry.get("declared_spec") != spec:
            errors.append(f"version spec mismatch: {ecosystem}:{name}")
        if not entry.get("source") or entry.get("modifications") != "none":
            errors.append(f"missing source or modification status: {ecosystem}:{name}")
        if entry.get("distribution_status") == "approved" and entry.get("license_spdx") is None:
            errors.append(f"unknown license cannot be approved: {ecosystem}:{name}")
    registered = set(by_key)
    extra = registered - {(ecosystem, name) for ecosystem, name, _ in expected}
    if extra:
        errors.append(f"register contains non-manifest dependencies: {sorted(extra)}")
    return errors


def render_notices(payload: dict) -> str:
    lines = [
        "# Third-Party Notices",
        "",
        "<!-- Generated by scripts/check_third_party_register.py; do not edit manually. -->",
        "",
        "This file is generated from `docs/research/third-party-register.yml`.",
        "Entries with `pending-confirmation` or `review-required` are not release-cleared.",
        "",
    ]
    for ecosystem in ("pypi", "npm"):
        lines.extend([f"## {ecosystem}", ""])
        for entry in sorted(payload["dependencies"], key=lambda item: item["name"].casefold()):
            if entry["ecosystem"] != ecosystem:
                continue
            license_value = entry["license_spdx"] or "UNKNOWN"
            lines.append(
                f"- `{entry['name']}` `{entry['declared_spec']}`; observed `{entry['observed_version']}`; "
                f"license `{license_value}` ({entry['license_status']}); source: {entry['source']}; "
                f"distribution: `{entry['distribution_status']}`."
            )
        lines.append("")
    lines.extend(
        [
            "## Reused Source Code",
            "",
            "No third-party source code is approved as reused code by RC-032.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    try:
        payload = load_register()
        errors = validate(payload)
    except (OSError, ValueError, KeyError, tomllib.TOMLDecodeError, json.JSONDecodeError, yaml.YAMLError) as exc:
        print(f"ERROR: third-party register failed: {exc}", file=sys.stderr)
        return 1
    if errors:
        for error in errors:
            print(f"ERROR: {error}", file=sys.stderr)
        return 1
    rendered = render_notices(payload)
    if args.write:
        NOTICE_PATH.write_text(rendered, encoding="utf-8")
        print(f"Wrote {NOTICE_PATH.relative_to(REPOSITORY_ROOT).as_posix()}")
        return 0
    if not NOTICE_PATH.is_file() or NOTICE_PATH.read_text(encoding="utf-8") != rendered:
        print("ERROR: THIRD_PARTY_NOTICES.md is stale; run with --write", file=sys.stderr)
        return 1
    print(f"Validated third-party register: {len(payload['dependencies'])} entries, no unregistered direct dependencies.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
