#!/usr/bin/env python3
"""RC ID: RC-130. Generate shared CSS variables and TypeScript token types."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "packages" / "ui" / "tokens.json"
CSS_OUTPUT = ROOT / "packages" / "ui" / "tokens.css"
TS_OUTPUT = ROOT / "packages" / "ui" / "tokens.ts"
SNAPSHOT_OUTPUT = ROOT / "packages" / "ui" / "token-snapshot.md"


def load_tokens() -> dict[str, Any]:
    document = json.loads(SOURCE.read_text(encoding="utf-8"))
    if document.get("schema_version") != 1:
        raise ValueError("tokens schema_version must be 1")
    if set(document) != {"schema_version", "themes", "static", "dimensions"}:
        raise ValueError("tokens must contain schema_version, themes, static, and dimensions")
    if set(document["themes"]) != {"light", "dark"}:
        raise ValueError("themes must contain light and dark")
    return document


def validate_values(document: dict[str, Any]) -> None:
    for section in ("light", "dark"):
        values = document["themes"][section]
        if not isinstance(values, dict) or not values:
            raise ValueError(f"theme {section} must be a non-empty object")
    for name in ("static", "dimensions"):
        values = document[name]
        if not isinstance(values, dict) or not values:
            raise ValueError(f"{name} must be a non-empty object")
    all_names = set(document["themes"]["light"]) | set(document["themes"]["dark"])
    all_names |= set(document["static"]) | set(document["dimensions"])
    if any(not isinstance(value, str) or not value.strip() for value in _all_values(document)):
        raise ValueError("token values must be non-empty strings")
    if len(all_names) != sum(len(values) for values in document["themes"].values()) + len(document["static"]) + len(document["dimensions"]) - len(document["themes"]["light"]):
        raise ValueError("token names must not overlap across sections")


def _all_values(document: dict[str, Any]) -> list[Any]:
    values: list[Any] = []
    for theme in document["themes"].values():
        values.extend(theme.values())
    values.extend(document["static"].values())
    values.extend(document["dimensions"].values())
    return values


def css_lines(document: dict[str, Any]) -> list[str]:
    lines = ["/* Generated by scripts/generate_design_tokens.py; do not edit manually. */", "", ":root {"]
    for section in ("light", "static", "dimensions"):
        values = document["themes"]["light"] if section == "light" else document[section]
        for name, value in values.items():
            lines.append(f"  --{name}: {value};")
    lines.extend(["}", "", ':root[data-theme="dark"] {'])
    for name, value in document["themes"]["dark"].items():
        lines.append(f"  --{name}: {value};")
    lines.extend(["}", ""])
    return lines


def ts_text(document: dict[str, Any]) -> str:
    payload = json.dumps(document, ensure_ascii=False, indent=2)
    return (
        "// Generated by scripts/generate_design_tokens.py; do not edit manually.\n"
        "// RC ID: RC-130.\n\n"
        f"export const designTokens = {payload} as const;\n\n"
        "export type ThemeTokenName = keyof typeof designTokens.themes.light;\n"
        "export type StaticTokenName = keyof typeof designTokens.static;\n"
        "export type DimensionTokenName = keyof typeof designTokens.dimensions;\n"
        "export type DesignTokenName = ThemeTokenName | StaticTokenName | DimensionTokenName;\n\n"
        "export function token(name: DesignTokenName): string {\n"
        "  return `var(--${name})`;\n"
        "}\n"
    )


def snapshot_text(document: dict[str, Any]) -> str:
    lines = [
        "# Design Token Snapshot",
        "",
        "<!-- Generated by scripts/generate_design_tokens.py; do not edit manually. -->",
        "",
        "| Token | Light | Dark |",
        "| --- | --- | --- |",
    ]
    light = document["themes"]["light"]
    dark = document["themes"]["dark"]
    for name in light:
        lines.append(f"| `--{name}` | `{light[name]}` | `{dark[name]}` |")
    lines.extend(["", "## Static and dimension tokens", "", "| Token | Value |", "| --- | --- |"])
    for section in ("static", "dimensions"):
        for name, value in document[section].items():
            lines.append(f"| `--{name}` | `{value}` |")
    return "\n".join(lines) + "\n"


def render(document: dict[str, Any]) -> tuple[str, str, str]:
    validate_values(document)
    return "\n".join(css_lines(document)), ts_text(document), snapshot_text(document)


def main() -> int:
    parser = argparse.ArgumentParser()
    action = parser.add_mutually_exclusive_group(required=True)
    action.add_argument("--write", action="store_true")
    action.add_argument("--check", action="store_true")
    args = parser.parse_args()
    try:
        css, typescript, snapshot = render(load_tokens())
    except (OSError, ValueError, json.JSONDecodeError) as error:
        print(f"ERROR: {error}")
        return 1
    if args.write:
        CSS_OUTPUT.write_text(css, encoding="utf-8")
        TS_OUTPUT.write_text(typescript, encoding="utf-8")
        SNAPSHOT_OUTPUT.write_text(snapshot, encoding="utf-8")
        print(f"Wrote {CSS_OUTPUT.relative_to(ROOT).as_posix()}, {TS_OUTPUT.relative_to(ROOT).as_posix()}, and {SNAPSHOT_OUTPUT.relative_to(ROOT).as_posix()}")
        return 0
    errors = []
    if not CSS_OUTPUT.is_file() or CSS_OUTPUT.read_text(encoding="utf-8") != css:
        errors.append("tokens.css is stale; run with --write")
    if not TS_OUTPUT.is_file() or TS_OUTPUT.read_text(encoding="utf-8") != typescript:
        errors.append("tokens.ts is stale; run with --write")
    if not SNAPSHOT_OUTPUT.is_file() or SNAPSHOT_OUTPUT.read_text(encoding="utf-8") != snapshot:
        errors.append("token-snapshot.md is stale; run with --write")
    if errors:
        for error in errors:
            print(f"ERROR: {error}")
        return 1
    print("Design token CSS and TypeScript outputs are current.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
