#!/usr/bin/env python3
"""RC ID: RC-213. Generate the shared core data-model artifacts."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, cast

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "docs/data-model/schema-v1.json"
OUTPUTS = {
    "erd": ROOT / "docs/data-model/erd.md",
    "migration": ROOT / "backend/migrations/0002_core_data_model.sql",
    "python": ROOT / "backend/src/prompt_optimizer/data_model.py",
    "typescript": ROOT / "frontend/src/generated/dataModel.ts",
}
SUPPORTED_TYPES = {"string", "integer", "boolean", "datetime", "json"}
SQL_TYPES = {
    "string": "TEXT",
    "integer": "INTEGER",
    "boolean": "INTEGER",
    "datetime": "TEXT",
    "json": "TEXT",
}
PYTHON_TYPES = {
    "string": "str",
    "integer": "int",
    "boolean": "bool",
    "datetime": "datetime",
    "json": "dict[str, Any]",
}
TYPESCRIPT_TYPES = {
    "string": "string",
    "integer": "number",
    "boolean": "boolean",
    "datetime": "string",
    "json": "Record<string, unknown>",
}


def load_schema() -> dict[str, Any]:
    document = cast(dict[str, Any], json.loads(SOURCE.read_text(encoding="utf-8")))
    if document.get("schema_version") != 1:
        raise ValueError("data model schema_version must be 1")
    entities = document.get("entities")
    if not isinstance(entities, list) or len(entities) != 10:
        raise ValueError("data model must define exactly 10 entities")
    tables: set[str] = set()
    names: set[str] = set()
    for entity in entities:
        if not isinstance(entity, dict):
            raise ValueError("each data model entity must be an object")
        table = entity.get("table")
        name = entity.get("name")
        fields = entity.get("fields")
        if not isinstance(table, str) or not isinstance(name, str) or table in tables or name in names:
            raise ValueError("entity names and tables must be unique strings")
        if not isinstance(fields, list) or not fields:
            raise ValueError(f"{name} must define fields")
        tables.add(table)
        names.add(name)
        primary_keys = 0
        field_names: set[str] = set()
        for field in fields:
            if not isinstance(field, dict) or not isinstance(field.get("name"), str):
                raise ValueError(f"{name} contains an invalid field")
            field_name = field["name"]
            if field_name in field_names or field.get("type") not in SUPPORTED_TYPES:
                raise ValueError(f"{name} contains a duplicate or unsupported field")
            field_names.add(field_name)
            if field.get("primary_key"):
                primary_keys += 1
            foreign_key = field.get("foreign_key")
            if foreign_key is not None and (
                not isinstance(foreign_key, dict)
                or not isinstance(foreign_key.get("table"), str)
                or not isinstance(foreign_key.get("column"), str)
            ):
                raise ValueError(f"{name}.{field_name} has an invalid foreign key")
        if primary_keys != 1:
            raise ValueError(f"{name} must have exactly one primary key")
    for entity in entities:
        for field in entity["fields"]:
            foreign_key = field.get("foreign_key")
            if foreign_key is not None and foreign_key["table"] not in tables:
                raise ValueError(f"unknown foreign table: {foreign_key['table']}")
    return document


def render(schema: dict[str, Any]) -> dict[str, str]:
    return {
        "erd": render_erd(schema),
        "migration": render_migration(schema),
        "python": render_python(schema),
        "typescript": render_typescript(schema),
    }


def render_erd(schema: dict[str, Any]) -> str:
    lines = [
        "# Rabbit Code Core Data Model",
        "",
        "<!-- Generated by scripts/generate_data_model.py; do not edit manually. -->",
        "<!-- RC ID: RC-213. -->",
        "",
        f"{chr(96) * 3}mermaid",
        "erDiagram",
    ]
    for entity in schema["entities"]:
        lines.append(f"    {entity['table']} {{")
        for field in entity["fields"]:
            marker = " PK" if field.get("primary_key") else ""
            lines.append(f"        {field['type']} {field['name']}{marker}")
        lines.append("    }")
    for entity in schema["entities"]:
        for field in entity["fields"]:
            foreign_key = field.get("foreign_key")
            if foreign_key is not None:
                lines.append(
                    f"    {foreign_key['table']} ||--o{{ {entity['table']} : {field['name']}"
                )
    lines.extend(
        [
            f"{chr(96) * 3}",
            "",
            "## Lifecycle and deletion",
            "",
            "Every entity has created_at, updated_at when mutable, a nullable "
            "deleted_at, and an integer version unless it is an immutable snapshot. "
            "Foreign-key cascades and SET NULL behavior are generated in the draft "
            "migration. credential_ref is an opaque SecretStore reference and "
            "path_ref is opaque or redacted; neither field stores the protected value "
            "by default.",
            "",
        ]
    )
    return "\n".join(lines)


def render_migration(schema: dict[str, Any]) -> str:
    lines = [
        "-- Generated by scripts/generate_data_model.py; do not edit manually.",
        "-- RC IDs: RC-213, RC-214. Draft migration; RC-214 owns transactional migration execution.",
        "PRAGMA foreign_keys = ON;",
        "BEGIN IMMEDIATE;",
        "CREATE TABLE IF NOT EXISTS schema_migrations (",
        "    version INTEGER PRIMARY KEY,",
        "    applied_at TEXT NOT NULL",
        ");",
        "",
    ]
    for entity in schema["entities"]:
        lines.append(f"CREATE TABLE IF NOT EXISTS {entity['table']} (")
        column_lines = []
        for field in entity["fields"]:
            column = f"    {field['name']} {SQL_TYPES[field['type']]}"
            if field.get("primary_key"):
                column += " PRIMARY KEY"
                if field.get("autoincrement"):
                    column += " AUTOINCREMENT"
            elif not field.get("nullable"):
                column += " NOT NULL"
            if "default" in field:
                column += f" DEFAULT {_sql_literal(field['default'], field['type'])}"
            column_lines.append(column)
        for field in entity["fields"]:
            foreign_key = field.get("foreign_key")
            if foreign_key is not None:
                column_lines.append(
                    "    FOREIGN KEY ({}) REFERENCES {}({}) ON DELETE {}".format(
                        field["name"],
                        foreign_key["table"],
                        foreign_key["column"],
                        foreign_key.get("on_delete", "RESTRICT"),
                    )
                )
        lines.append(",\n".join(column_lines))
        lines.extend([");", ""])
        for index in entity.get("indexes", []):
            columns = ", ".join(index["columns"])
            lines.append(
                f"CREATE INDEX IF NOT EXISTS {index['name']} ON {entity['table']}({columns});"
            )
        lines.append("")
    lines.extend(
        [
            "INSERT OR IGNORE INTO schema_migrations(version, applied_at)",
            "VALUES (2, CURRENT_TIMESTAMP);",
            "PRAGMA user_version = 2;",
            "COMMIT;",
            "",
        ]
    )
    return "\n".join(lines)


def render_python(schema: dict[str, Any]) -> str:
    lines = [
        "# Generated by scripts/generate_data_model.py; do not edit manually.",
        "# RC ID: RC-213.",
        "",
        "from __future__ import annotations",
        "",
        "from datetime import datetime",
        "from typing import Any",
        "",
        "from pydantic import BaseModel, Field",
        "",
        "SCHEMA_VERSION = 1",
        "",
    ]
    for entity in schema["entities"]:
        lines.append(f"class {entity['python_name']}(BaseModel):")
        for field in entity["fields"]:
            annotation = PYTHON_TYPES[field["type"]]
            if field.get("nullable"):
                annotation += " | None"
            lines.append(f"    {field['name']}: {annotation}{_python_default(field)}")
        lines.append("")
    return "\n".join(lines)


def render_typescript(schema: dict[str, Any]) -> str:
    lines = [
        "// Generated by scripts/generate_data_model.py; do not edit manually.",
        "// RC ID: RC-213.",
        "",
        "export const CORE_DATA_MODEL_SCHEMA_VERSION = 1 as const;",
        "",
    ]
    for entity in schema["entities"]:
        lines.append(f"export interface {entity['typescript_name']} {{")
        for field in entity["fields"]:
            nullable = " | null" if field.get("nullable") else ""
            lines.append(f"  {field['name']}: {TYPESCRIPT_TYPES[field['type']]}{nullable};")
        lines.extend(["}", ""])
    return "\n".join(lines)


def _sql_literal(value: object, field_type: str) -> str:
    if field_type == "boolean":
        return "1" if value else "0"
    if field_type == "json":
        encoded = json.dumps(value, ensure_ascii=False).replace("'", "''")
        return f"'{encoded}'"
    if isinstance(value, (int, float)):
        return str(value)
    return "'" + str(value).replace("'", "''") + "'"


def _python_default(field: dict[str, Any]) -> str:
    if field.get("nullable"):
        return " = None"
    if "default" not in field:
        return ""
    if field["type"] == "json":
        return " = Field(default_factory=dict)"
    return f" = {field['default']!r}"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    action = parser.add_mutually_exclusive_group(required=True)
    action.add_argument("--write", action="store_true")
    action.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    try:
        outputs = render(load_schema())
    except (OSError, ValueError, json.JSONDecodeError) as error:
        print(f"ERROR: {error}")
        return 1
    if args.write:
        for name, path in OUTPUTS.items():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(outputs[name], encoding="utf-8")
        print("Wrote core data-model artifacts.")
        return 0
    errors = [
        f"{path.relative_to(ROOT).as_posix()} is stale; run with --write"
        for name, path in OUTPUTS.items()
        if not path.is_file() or path.read_text(encoding="utf-8") != outputs[name]
    ]
    if errors:
        for message in errors:
            print(f"ERROR: {message}")
        return 1
    print("Core data-model artifacts are current.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
